#pragma once
// Auto-generated from web/index.html - do not edit manually
// Run tools/generate_web_index.ps1 after changing web/index.html

#include <pgmspace.h>

const char WEB_INDEX_HTML[] PROGMEM =
  "<!DOCTYPE html>\n"
  "<html lang=\"ko\">\n"
  "<head>\n"
  "<meta charset=\"UTF-8\">\n"
  "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no, viewport-fit=cover\">\n"
  "<title>RC Car Controller</title>\n"
  "<style>\n"
  "  @import url(\"https://fonts.googleapis.com/css2?family=Share+Tech+Mono&family=Orbitron:wght@400;700&display=swap\");\n"
  "\n"
  "  :root {\n"
  "    --bg: #1a1a2e;\n"
  "    --panel: #16213e;\n"
  "    --green: #4ade80;\n"
  "    --orange: #f97316;\n"
  "    --red: #ef4444;\n"
  "    --blue: #60a5fa;\n"
  "    --text: #e2e8f0;\n"
  "    --hud: rgba(255, 255, 255, 0.12);\n"
  "    --btn-active: rgba(74, 222, 128, 0.3);\n"
  "  }\n"
  "\n"
  "  * { box-sizing: border-box; margin: 0; padding: 0; touch-action: manipulation; }\n"
  "  html, body { min-height: 100%; }\n"
  "  body { background: #3a7bd5; min-height: 100vh; font-family: \"Share Tech Mono\", monospace; overflow: hidden; }\n"
  "\n"
  "  #app {\n"
  "    position: fixed; inset: 0; width: 100vw; height: 100vh;\n"
  "    background: var(--bg); border-radius: 0; overflow: hidden;\n"
  "    display: flex; flex-direction: column;\n"
  "  }\n"
  "\n"
  "  #stream-wrap {\n"
  "    position: relative; width: 100%; flex: 0 0 38dvh;\n"
  "    min-height: 220px; background: #0a0a1a; overflow: hidden;\n"
  "    display: flex; align-items: center; justify-content: center;\n"
  "  }\n"
  "  #stream-wrap::before {\n"
  "    content: \"NO SIGNAL\"; position: absolute;\n"
  "    color: rgba(255,255,255,0.15); font-family: \"Orbitron\", sans-serif;\n"
  "    font-size: 13px; letter-spacing: 4px; animation: blink 2s infinite;\n"
  "  }\n"
  "  @keyframes blink { 0%,100%{opacity:1} 50%{opacity:0.3} }\n"
  "\n"
  "  #stream {\n"
  "    width: 100%; height: 100%; object-fit: cover; display: block;\n"
  "    position: relative; z-index: 1; background: #111;\n"
  "  }\n"
  "  #stream[src=\"\"] { opacity: 0; }\n"
  "  #stream-canvas {\n"
  "    width: 100%; height: 100%; display: none;\n"
  "    position: relative; z-index: 1; background: #111;\n"
  "  }\n"
  "  #stream-canvas.visible { display: block; }\n"
  "  #talk-overlay {\n"
  "    position: absolute; inset: 0; z-index: 3;\n"
  "    display: none; align-items: center; justify-content: center;\n"
  "    background: rgba(8, 12, 24, 0.72);\n"
  "    backdrop-filter: blur(3px);\n"
  "    color: #fef3c7;\n"
  "    font-family: \"Orbitron\", sans-serif;\n"
  "    font-size: 13px; letter-spacing: 2px; text-align: center;\n"
  "  }\n"
  "  #talk-overlay.visible { display: flex; }\n"
  "  #talk-overlay span {\n"
  "    display: inline-block;\n"
  "    padding: 10px 14px;\n"
  "    border: 1px solid rgba(249, 115, 22, 0.45);\n"
  "    border-radius: 10px;\n"
  "    background: rgba(146, 64, 14, 0.4);\n"
  "    box-shadow: 0 0 24px rgba(249, 115, 22, 0.18);\n"
  "  }\n"
  "\n"
  "  #hud {\n"
  "    position: absolute; top: 0; left: 0; right: 0;\n"
  "    padding: 6px 8px; display: flex; justify-content: flex-start;\n"
  "    align-items: flex-start; pointer-events: none; z-index: 2;\n"
  "  }\n"
  "  #hud-left {\n"
  "    background: var(--hud); backdrop-filter: blur(4px);\n"
  "    border-radius: 5px; padding: 3px 6px; font-size: 8px;\n"
  "    color: #fff; line-height: 1.2; border: 1px solid rgba(255,255,255,0.15);\n"
  "    display: inline-flex; align-items: center; gap: 8px;\n"
  "    letter-spacing: 0.3px;\n"
  "  }\n"
  "  #hud-left span { display: inline; white-space: nowrap; }\n"
  "  .bat-val { color: var(--green); }\n"
  "  .rssi-val { color: var(--blue); }\n"
  "  .res-val { color: #fef08a; }\n"
  "  .hud-hidden { display: none !important; }\n"
  "  .ap-setup-only #stream-wrap { display: none; }\n"
  "  .ap-setup-only #control-panel { display: none; }\n"
  "  .ap-setup-only #btn-led,\n"
  "  .ap-setup-only #btn-snap,\n"
  "  .ap-setup-only #btn-talk,\n"
  "  .ap-setup-only #btn-rec { display: none; }\n"
  "  .ap-setup-only #toolbar { border-top: none; }\n"
  "  .ap-setup-only #btn-net {\n"
  "    flex: 1;\n"
  "    background: rgba(249, 115, 22, 0.16);\n"
  "    color: var(--orange);\n"
  "  }\n"
  "  #setup-summary {\n"
  "    display: none;\n"
  "    margin: 18px 14px 10px;\n"
  "    padding: 16px 18px;\n"
  "    border-radius: 14px;\n"
  "    background: linear-gradient(160deg, rgba(22,33,62,0.96), rgba(15,23,42,0.96));\n"
  "    border: 1px solid rgba(255,255,255,0.08);\n"
  "    color: var(--text);\n"
  "    line-height: 1.6;\n"
  "  }\n"
  "  .ap-setup-only #setup-summary { display: block; }\n"
  "  #setup-summary h2 {\n"
  "    font-family: \"Orbitron\", sans-serif;\n"
  "    font-size: 14px;\n"
  "    letter-spacing: 1px;\n"
  "    color: #fef08a;\n"
  "    margin-bottom: 10px;\n"
  "  }\n"
  "  #setup-summary p {\n"
  "    font-size: 12px;\n"
  "    color: rgba(255,255,255,0.72);\n"
  "    margin-bottom: 8px;\n"
  "  }\n"
  "  #setup-summary strong { color: #fff; }\n"
  "\n"
  "  /* AP모드 배너 */\n"
  "  #ap-banner {\n"
  "    display: none; background: #92400e; color: #fef3c7;\n"
  "    font-size: 11px; text-align: center; padding: 5px 10px;\n"
  "    font-family: \"Orbitron\", sans-serif; letter-spacing: 1px;\n"
  "    border-bottom: 1px solid #b45309;\n"
  "  }\n"
  "  #ap-banner.visible { display: block; }\n"
  "\n"
  "  #toolbar {\n"
  "    display: flex; background: var(--panel);\n"
  "    border-top: 1px solid rgba(255,255,255,0.06);\n"
  "    border-bottom: 1px solid rgba(255,255,255,0.06);\n"
  "  }\n"
  "  .tb-btn {\n"
  "    flex: 1; padding: 11px 4px;\n"
  "    font-family: \"Orbitron\", sans-serif; font-size: 10px;\n"
  "    font-weight: 700; letter-spacing: 0.5px; color: var(--text);\n"
  "    background: transparent; border: none;\n"
  "    border-right: 1px solid rgba(255,255,255,0.06);\n"
  "    cursor: pointer; transition: background 0.15s, color 0.15s;\n"
  "    user-select: none;\n"
  "  }\n"
  "  .tb-btn:last-child { border-right: none; }\n"
  "  .tb-btn:active, .tb-btn.active { background: var(--btn-active); color: var(--green); }\n"
  "  .tb-btn.rec-btn { background: var(--red); color: #fff; }\n"
  "  .tb-btn.rec-btn.active { background: #b91c1c; animation: pulse 1s infinite; }\n"
  "  .tb-btn.net-btn { color: var(--orange); }\n"
  "  @keyframes pulse { 0%,100%{opacity:1} 50%{opacity:0.6} }\n"
  "\n"
  "  #control-panel {\n"
  "    background: #1e1e2e; padding: 10px 10px calc(14px + env(safe-area-inset-bottom));\n"
  "    flex: 1 1 auto; min-height: 0; display: flex; flex-direction: column;\n"
  "  }\n"
  "  #mode-label {\n"
  "    text-align: center; font-size: 10px;\n"
  "    color: rgba(255,255,255,0.35); letter-spacing: 2px;\n"
  "    margin-bottom: 8px; font-family: \"Orbitron\", sans-serif;\n"
  "  }\n"
  "  #joystick-outer {\n"
  "    width: 100%; flex: 1 1 auto; min-height: 220px;\n"
  "    background: #111122; border-radius: 12px;\n"
  "    border: 1px solid rgba(255,255,255,0.07);\n"
  "    display: flex; align-items: center; justify-content: center;\n"
  "    position: relative; overflow: hidden;\n"
  "  }\n"
  "  #joystick-outer::before {\n"
  "    content: \"\"; position: absolute; inset: 0;\n"
  "    background-image: linear-gradient(rgba(255,255,255,0.03) 1px, transparent 1px),\n"
  "      linear-gradient(90deg, rgba(255,255,255,0.03) 1px, transparent 1px);\n"
  "    background-size: 30px 30px;\n"
  "  }\n"
  "  #joystick-outer::after {\n"
  "    content: \"\"; position: absolute; inset: 0;\n"
  "    background-image: linear-gradient(rgba(255,255,255,0.06) 1px, transparent 1px),\n"
  "      linear-gradient(90deg, rgba(255,255,255,0.06) 1px, transparent 1px);\n"
  "    background-size: 100% 50%, 50% 100%; background-position: center;\n"
  "  }\n"
  "  #joystick-ring {\n"
  "    width: 180px; height: 180px; border-radius: 50%;\n"
  "    border: 1px solid rgba(255,255,255,0.18); position: absolute; z-index: 1;\n"
  "    box-shadow: 0 0 0 30px rgba(255,255,255,0.02), 0 0 0 60px rgba(255,255,255,0.015);\n"
  "  }\n"
  "  #joystick-knob {\n"
  "    width: 90px; height: 90px; border-radius: 50%;\n"
  "    background: radial-gradient(circle at 35% 35%, #f0e060, #c8a800);\n"
  "    border: 8px solid rgba(180,150,0,0.4); position: absolute;\n"
  "    cursor: grab; touch-action: none; transition: border-color 0.1s;\n"
  "    box-shadow: 0 4px 20px rgba(0,0,0,0.5), inset 0 2px 6px rgba(255,255,255,0.2);\n"
  "    z-index: 10;\n"
  "  }\n"
  "  #joystick-knob:active { cursor: grabbing; border-color: rgba(255,220,0,0.6); }\n"
  "  .btn-on { box-shadow: inset 0 0 0 2px var(--green); color: var(--green); }\n"
  "\n"
  "  /* ===== WiFi 패널 오버레이 ===== */\n"
  "  #wifi-overlay {\n"
  "    display: none; position: fixed; inset: 0; z-index: 100;\n"
  "    background: rgba(0,0,0,0.85); backdrop-filter: blur(6px);\n"
  "    align-items: flex-end; justify-content: center;\n"
  "  }\n"
  "  #wifi-overlay.open { display: flex; }\n"
  "\n"
  "  #wifi-panel {\n"
  "    background: #16213e; width: 100%; max-width: 480px;\n"
  "    border-radius: 20px 20px 0 0; padding: 20px 16px calc(24px + env(safe-area-inset-bottom));\n"
  "    border-top: 1px solid rgba(255,255,255,0.1);\n"
  "    max-height: 80vh; overflow-y: auto;\n"
  "  }\n"
  "  #wifi-panel h2 {\n"
  "    font-family: \"Orbitron\", sans-serif; font-size: 13px;\n"
  "    color: var(--orange); letter-spacing: 2px; margin-bottom: 14px;\n"
  "    display: flex; justify-content: space-between; align-items: center;\n"
  "  }\n"
  "  #wifi-panel h2 button {\n"
  "    background: none; border: none; color: rgba(255,255,255,0.5);\n"
  "    font-size: 18px; cursor: pointer; padding: 0 4px;\n"
  "  }\n"
  "\n"
  "  #wifi-scan-list {\n"
  "    display: flex; flex-direction: column; gap: 6px; margin-bottom: 14px;\n"
  "    min-height: 48px;\n"
  "  }\n"
  "  .wifi-item {\n"
  "    display: flex; align-items: center; justify-content: space-between;\n"
  "    background: rgba(255,255,255,0.05); border-radius: 10px;\n"
  "    padding: 10px 12px; cursor: pointer; border: 1px solid transparent;\n"
  "    transition: border-color 0.15s, background 0.15s;\n"
  "  }\n"
  "  .wifi-item:active, .wifi-item.selected { border-color: var(--orange); background: rgba(249,115,22,0.1); }\n"
  "  .wifi-item-ssid { font-size: 13px; color: var(--text); }\n"
  "  .wifi-item-meta { font-size: 11px; color: rgba(255,255,255,0.4); display: flex; gap: 8px; align-items: center; }\n"
  "  .wifi-lock { color: var(--orange); font-size: 10px; }\n"
  "  .wifi-saved { color: var(--green); font-size: 10px; }\n"
  "\n"
  "  #wifi-pw-row {\n"
  "    display: none; margin-bottom: 10px;\n"
  "  }\n"
  "  #wifi-pw-row.visible { display: block; }\n"
  "  #wifi-pw-input {\n"
  "    width: 100%; padding: 11px 12px; background: #0f172a;\n"
  "    border: 1px solid rgba(255,255,255,0.15); border-radius: 10px;\n"
  "    color: var(--text); font-family: \"Share Tech Mono\", monospace;\n"
  "    font-size: 14px; outline: none;\n"
  "  }\n"
  "  #wifi-pw-input:focus { border-color: var(--orange); }\n"
  "\n"
  "  #wifi-connect-btn {\n"
  "    width: 100%; padding: 13px; background: var(--orange);\n"
  "    border: none; border-radius: 12px; color: #fff;\n"
  "    font-family: \"Orbitron\", sans-serif; font-size: 12px;\n"
  "    font-weight: 700; letter-spacing: 1px; cursor: pointer;\n"
  "    transition: background 0.15s; margin-bottom: 8px;\n"
  "  }\n"
  "  #wifi-connect-btn:active { background: #c2410c; }\n"
  "  #wifi-connect-btn:disabled { background: rgba(255,255,255,0.15); cursor: not-allowed; }\n"
  "\n"
  "  #wifi-scan-btn {\n"
  "    width: 100%; padding: 10px; background: transparent;\n"
  "    border: 1px solid rgba(255,255,255,0.15); border-radius: 10px;\n"
  "    color: rgba(255,255,255,0.5); font-family: \"Share Tech Mono\", monospace;\n"
  "    font-size: 12px; cursor: pointer; transition: border-color 0.15s;\n"
  "  }\n"
  "  #wifi-scan-btn:active { border-color: var(--blue); color: var(--blue); }\n"
  "\n"
  "  #wifi-status-msg {\n"
  "    text-align: center; font-size: 11px; color: rgba(255,255,255,0.4);\n"
  "    margin-top: 10px; min-height: 16px;\n"
  "  }\n"
  "  #wifi-status-msg.ok { color: var(--green); }\n"
  "  #wifi-status-msg.err { color: var(--red); }\n"
  "\n"
  "  /* ===== 브로커 모드 전환 안내 ===== */\n"
  "  #broker-hint {\n"
  "    display: none; background: #14532d; border: 1px solid #166534;\n"
  "    border-radius: 10px; padding: 10px 12px; margin-bottom: 10px;\n"
  "    font-size: 11px; color: #bbf7d0; line-height: 1.6;\n"
  "  }\n"
  "\n"
  "  .scan-spinner { display: inline-block; animation: spin 0.8s linear infinite; }\n"
  "  @keyframes spin { to { transform: rotate(360deg); } }\n"
  "\n"
  "  @media (min-width: 768px) {\n"
  "    body { display: flex; justify-content: center; align-items: center; padding: 20px; overflow: auto; }\n"
  "    #app {\n"
  "      position: relative; inset: auto;\n"
  "      width: min(420px, 100vw);\n"
  "      min-height: min(900px, calc(100dvh - 40px));\n"
  "      height: min(900px, calc(100dvh - 40px));\n"
  "      border-radius: 16px;\n"
  "      box-shadow: 0 20px 60px rgba(0,0,0,0.5);\n"
  "      border: 1px solid rgba(255,255,255,0.08);\n"
  "    }\n"
  "    #stream-wrap { flex-basis: 260px; min-height: 260px; }\n"
  "    #joystick-outer { min-height: 220px; }\n"
  "    #wifi-panel { border-radius: 16px; margin: auto; }\n"
  "    #wifi-overlay { align-items: center; }\n"
  "  }\n"
  "</style>\n"
  "</head>\n"
  "<body>\n"
  "<div id=\"app\">\n"
  "  <div id=\"ap-banner\" class=\"visible\">⚡ AP 로컬 모드 — 192.168.4.1 직접 연결 중</div>\n"
  "\n"
  "  <section id=\"setup-summary\">\n"
  "    <h2>설정 전용 AP 모드</h2>\n"
  "    <p><strong>이 모드에서는 스트리밍, 조종, 오디오를 제공하지 않습니다.</strong></p>\n"
  "    <p>하단의 <strong>NET</strong> 버튼을 눌러 Wi-Fi를 선택하고 저장하면 보드가 재부팅 없이 브로커 모드로 전환됩니다.</p>\n"
  "  </section>\n"
  "\n"
  "  <div id=\"stream-wrap\">\n"
  "    <img id=\"stream\" src=\"\" alt=\"stream\" crossorigin=\"anonymous\">\n"
  "    <canvas id=\"stream-canvas\"></canvas>\n"
  "    <div id=\"talk-overlay\"><span>TALK MODE<br>VOICE TO CAR</span></div>\n"
  "    <div id=\"hud\">\n"
  "      <div id=\"hud-left\">\n"
  "        <span>BAT : <span class=\"bat-val\" id=\"bat-val\">0%</span></span>\n"
  "        <span>SIG : <span class=\"rssi-val\" id=\"rssi-val\">100%</span></span>\n"
  "        <span class=\"res-val\" id=\"res-label\">QVGA</span>\n"
  "        <span>WS : <span id=\"ws-val\">--</span></span>\n"
  "        <span>RTT : <span id=\"rtt-val\">--</span></span>\n"
  "        <span>VID : <span id=\"video-age-val\">--</span></span>\n"
  "        <span class=\"hud-hidden\" id=\"conn-label\">connecting</span>\n"
  "      </div>\n"
  "    </div>\n"
  "  </div>\n"
  "\n"
  "  <div id=\"toolbar\">\n"
  "    <button class=\"tb-btn\" id=\"btn-led\" type=\"button\">LED</button>\n"
  "    <button class=\"tb-btn net-btn\" id=\"btn-net\" type=\"button\">NET</button>\n"
  "    <button class=\"tb-btn\" id=\"btn-snap\" type=\"button\">SNAP</button>\n"
  "    <button class=\"tb-btn\" id=\"btn-talk\" type=\"button\">TALK</button>\n"
  "    <button class=\"tb-btn rec-btn\" id=\"btn-rec\" type=\"button\">REC</button>\n"
  "  </div>\n"
  "\n"
  "  <div id=\"control-panel\">\n"
  "    <div id=\"mode-label\">조종 모드</div>\n"
  "    <div id=\"joystick-outer\">\n"
  "      <div id=\"joystick-ring\"></div>\n"
  "      <div id=\"joystick-knob\"></div>\n"
  "    </div>\n"
  "  </div>\n"
  "</div>\n"
  "\n"
  "<!-- WiFi 전환 패널 오버레이 -->\n"
  "<div id=\"wifi-overlay\">\n"
  "  <div id=\"wifi-panel\">\n"
  "    <h2>\n"
  "      <span>🌐 네트워크 전환</span>\n"
  "      <button onclick=\"closeWifiPanel()\">✕</button>\n"
  "    </h2>\n"
  "    <div id=\"broker-hint\">\n"
  "      ✅ Wi-Fi 선택 후 <b>연결</b>을 누르면 브로커 모드로 전환됩니다.<br>\n"
  "      저장 후 재부팅 없이 브로커 모드로 전환됩니다.\n"
  "    </div>\n"
  "    <div id=\"wifi-scan-list\">\n"
  "      <div style=\"color:rgba(255,255,255,0.3);font-size:12px;text-align:center;padding:12px\">\n"
  "        스캔 버튼을 눌러 주변 Wi-Fi를 검색하세요\n"
  "      </div>\n"
  "    </div>\n"
  "    <div id=\"wifi-pw-row\">\n"
  "      <input id=\"wifi-pw-input\" type=\"password\" placeholder=\"Wi-Fi 비밀번호 입력\" autocomplete=\"off\">\n"
  "    </div>\n"
  "    <button id=\"wifi-connect-btn\" disabled onclick=\"doWifiConnect()\">연결</button>\n"
  "    <button id=\"wifi-scan-btn\" onclick=\"doWifiScan()\">📡 주변 Wi-Fi 스캔</button>\n"
  "    <div id=\"wifi-status-msg\"></div>\n"
  "  </div>\n"
  "</div>\n"
  "\n"
  "<canvas id=\"snapshot-canvas\" hidden></canvas>\n"
  "\n"
  "<script>\n"
  "// ============================================================\n"
  "// 모드 감지: AP모드면 ESP32 직접, 아니면 broker WebSocket\n"
  "// ============================================================\n"
  "\n"
  "// 페이지가 192.168.4.1 또는 로컬 ESP32 IP에서 열린 경우 → AP/로컬 모드\n"
  "// broker(Oracle VM) IP에서 열린 경우 → broker 모드\n"
  "const isApOrLocal = (() => {\n"
  "  const h = location.hostname;\n"
  "  // 192.168.x.x / 10.x.x.x / 172.16-31.x.x → 로컬 ESP32\n"
  "  return /^192\\.168\\.|^10\\.|^172\\.(1[6-9]|2\\d|3[01])\\./.test(h);\n"
  "})();\n"
  "\n"
  "const ESP32_BASE = isApOrLocal ? `http://${location.host}` : null;\n"
  "const brokerUrl = isApOrLocal ? null\n"
  "  : `${location.protocol === \"https:\" ? \"wss\" : \"ws\"}://${location.host}/client`;\n"
  "const defaultDeviceId = \"rc-car-01\";\n"
  "const DEFAULT_CAMERA_QUALITY = \"QVGA\";\n"
  "const queryDeviceId = new URLSearchParams(location.search).get(\"deviceId\");\n"
  "let deviceId = (queryDeviceId && queryDeviceId.trim()) || defaultDeviceId;\n"
  "const pinnedDeviceId = Boolean(queryDeviceId && queryDeviceId.trim());\n"
  "const qualityList = [\"QVGA\", \"VGA\", \"SVGA\", \"UXGA\"];\n"
  "\n"
  "let ws = null;\n"
  "let wsReady = false;\n"
  "const WS_PING_INTERVAL_MS = 10000;\n"
  "let wsPingTimer = 0;\n"
  "let driveMode = true;\n"
  "let resIdx = qualityList.indexOf(DEFAULT_CAMERA_QUALITY);\n"
  "if (resIdx < 0) resIdx = 0;\n"
  "let ledOn = false;\n"
  "let talkOn = false;\n"
  "let talkPointerId = null;\n"
  "let recOn = false;\n"
  "let streamUrl = \"\";\n"
  "let snapshotInFlight = false;\n"
  "let wakeLockSentinel = null;\n"
  "let apModeActive = isApOrLocal;\n"
  "let apVideoLoopActive = false;\n"
  "let defaultQualityApplied = false;\n"
  "let apVideoPaused = false;\n"
  "let apAudioPaused = false;\n"
  "let apResumeVideoTimer = 0;\n"
  "let apResumeAudioTimer = 0;\n"
  "let selectedSsidSecure = true;\n"
  "let brokerCanvasActive = false;\n"
  "let brokerFrameBusy = false;\n"
  "let brokerQueuedFrame = null;\n"
  "let wsHudState = apModeActive ? \"AP\" : \"OFF\";\n"
  "let lastPingSentAt = 0;\n"
  "let lastPingRttMs = null;\n"
  "let lastFrameDrawAt = 0;\n"
  "let smoothedVideoAgeMs = 0;\n"
  "let hudTimer = 0;\n"
  "\n"
  "// AP모드 상태 표시\n"
  "const apBanner = document.getElementById(\"ap-banner\");\n"
  "apBanner.classList.toggle(\"visible\", apModeActive);\n"
  "\n"
  "const streamEl = document.getElementById(\"stream\");\n"
  "const streamCanvas = document.getElementById(\"stream-canvas\");\n"
  "const streamCanvasCtx = streamCanvas.getContext(\"2d\", { alpha: false });\n"
  "const talkOverlay = document.getElementById(\"talk-overlay\");\n"
  "const connLabel = document.getElementById(\"conn-label\");\n"
  "const batVal = document.getElementById(\"bat-val\");\n"
  "const rssiVal = document.getElementById(\"rssi-val\");\n"
  "const resLabel = document.getElementById(\"res-label\");\n"
  "const wsVal = document.getElementById(\"ws-val\");\n"
  "const rttVal = document.getElementById(\"rtt-val\");\n"
  "const videoAgeVal = document.getElementById(\"video-age-val\");\n"
  "const modeLabel = document.getElementById(\"mode-label\");\n"
  "const btnLed = document.getElementById(\"btn-led\");\n"
  "const btnNet = document.getElementById(\"btn-net\");\n"
  "const btnSnap = document.getElementById(\"btn-snap\");\n"
  "const btnTalk = document.getElementById(\"btn-talk\");\n"
  "const btnRec = document.getElementById(\"btn-rec\");\n"
  "const knob = document.getElementById(\"joystick-knob\");\n"
  "const outerEl = document.getElementById(\"joystick-outer\");\n"
  "const snapshotCanvas = document.getElementById(\"snapshot-canvas\");\n"
  "\n"
  "// ============================================================\n"
  "// AP 모드: HTTP POST 기반 컨트롤\n"
  "// ============================================================\n"
  "async function apPost(path, payload) {\n"
  "  try {\n"
  "    const res = await fetch(`${ESP32_BASE}${path}`, {\n"
  "      method: \"POST\",\n"
  "      headers: { \"Content-Type\": \"application/json\" },\n"
  "      body: JSON.stringify(payload)\n"
  "    });\n"
  "    return res.ok;\n"
  "  } catch {\n"
  "    return false;\n"
  "  }\n"
  "}\n"
  "\n"
  "async function apGet(path) {\n"
  "  try {\n"
  "    const res = await fetch(`${ESP32_BASE}${path}`);\n"
  "    return await res.json();\n"
  "  } catch {\n"
  "    return null;\n"
  "  }\n"
  "}\n"
  "\n"
  "// AP 모드 상태 폴링\n"
  "let apStatusTimer = null;\n"
  "function startApStatusPoll() {\n"
  "  if (apStatusTimer) return;\n"
  "  apStatusTimer = setInterval(async () => {\n"
  "    const s = await apGet(\"/api/status\");\n"
  "    if (!s) { connLabel.textContent = \"ESP32 응답없음\"; return; }\n"
  "    connLabel.textContent = `AP ${s.ip}`;\n"
  "    if (typeof s.batteryPct === \"number\") batVal.textContent = `${s.batteryPct}%`;\n"
  "    if (typeof s.rssi === \"number\") rssiVal.textContent = `${signalPercentFromRssi(s.rssi)}%`;\n"
  "  }, 1500);\n"
  "}\n"
  "\n"
  "// ============================================================\n"
  "// broker 모드: WebSocket 기반\n"
  "// ============================================================\n"
  "const recorderState = { stream: null, recorder: null, chunks: [], renderTimer: null };\n"
  "\n"
  "const audioState = {\n"
  "  ctx: null, mixDestination: null, sampleRate: 16000,\n"
  "  enabled: false, nextPlayAt: 0, maxLeadSeconds: 0.6,\n"
  "  targetLeadSeconds: 0.12, lastSeqByDevice: new Map(), activeSources: new Set()\n"
  "};\n"
  "\n"
  "const talkAudioState = {\n"
  "  ctx: null, stream: null, source: null, processor: null,\n"
  "  muteGain: null, pendingSamples: [], seq: 0, stepIndex: 0, sentChunks: 0,\n"
  "  captureSampleRate: 16000, targetSampleRate: 16000, uploadQueue: [], uploadInFlight: false\n"
  "};\n"
  "\n"
  "function setButtonState(button, active) {\n"
  "  button.classList.toggle(\"active\", active);\n"
  "  button.classList.toggle(\"btn-on\", active && button !== btnRec);\n"
  "}\n"
  "\n"
  "// 공통 컨트롤 함수 - AP/broker 자동 분기\n"
  "function sendCtrl(throttle, steering) {\n"
  "  if (apModeActive) {\n"
  "    apPost(\"/api/control\", { throttle, steering });\n"
  "  } else {\n"
  "    send({ type: \"ctrl\", deviceId, throttle, steering });\n"
  "  }\n"
  "}\n"
  "\n"
  "function sendLed(enabled) {\n"
  "  if (apModeActive) {\n"
  "    apPost(\"/api/control\", { ledEnabled: enabled });\n"
  "  } else {\n"
  "    send({ type: \"led\", deviceId, enabled });\n"
  "  }\n"
  "}\n"
  "\n"
  "function sendMode(mode) {\n"
  "  if (!apModeActive) {\n"
  "    send({ type: \"mode\", deviceId, mode });\n"
  "  }\n"
  "}\n"
  "\n"
  "function send(payload) {\n"
  "  if (!wsReady || !ws || ws.readyState !== WebSocket.OPEN) return false;\n"
  "  ws.send(JSON.stringify(payload));\n"
  "  return true;\n"
  "}\n"
  "\n"
  "function wait(ms) { return new Promise(r => setTimeout(r, ms)); }\n"
  "\n"
  "async function requestWakeLock() {\n"
  "  if (!(\"wakeLock\" in navigator) || document.hidden || wakeLockSentinel) return;\n"
  "  try {\n"
  "    wakeLockSentinel = await navigator.wakeLock.request(\"screen\");\n"
  "    wakeLockSentinel.addEventListener(\"release\", () => { wakeLockSentinel = null; }, { once: true });\n"
  "  } catch { wakeLockSentinel = null; }\n"
  "}\n"
  "\n"
  "async function releaseWakeLock() {\n"
  "  if (!wakeLockSentinel) return;\n"
  "  try { await wakeLockSentinel.release(); } catch {}\n"
  "  wakeLockSentinel = null;\n"
  "}\n"
  "\n"
  "function signalPercentFromRssi(rssi) {\n"
  "  if (typeof rssi !== \"number\") return null;\n"
  "  return Math.max(0, Math.min(100, Math.round(((rssi + 100) / 50) * 100)));\n"
  "}\n"
  "\n"
  "function formatAgeMs(ageMs) {\n"
  "  if (typeof ageMs !== \"number\" || !Number.isFinite(ageMs) || ageMs < 0) return \"--\";\n"
  "  return `${Math.round(ageMs)}ms`;\n"
  "}\n"
  "\n"
  "function updateHudMetrics() {\n"
  "  wsVal.textContent = wsHudState;\n"
  "  rttVal.textContent = lastPingRttMs === null ? \"--\" : `${Math.round(lastPingRttMs)}ms`;\n"
  "  if (!lastFrameDrawAt) {\n"
  "    videoAgeVal.textContent = \"--\";\n"
  "    return;\n"
  "  }\n"
  "\n"
  "  const rawAgeMs = Date.now() - lastFrameDrawAt;\n"
  "  if (rawAgeMs >= 3000) {\n"
  "    videoAgeVal.textContent = \"LOST\";\n"
  "    return;\n"
  "  }\n"
  "\n"
  "  if (smoothedVideoAgeMs <= 0 || rawAgeMs < smoothedVideoAgeMs) {\n"
  "    smoothedVideoAgeMs = rawAgeMs;\n"
  "  } else {\n"
  "    smoothedVideoAgeMs = (smoothedVideoAgeMs * 0.82) + (rawAgeMs * 0.18);\n"
  "  }\n"
  "\n"
  "  const quantizedAgeMs = Math.round(smoothedVideoAgeMs / 25) * 25;\n"
  "  videoAgeVal.textContent = formatAgeMs(quantizedAgeMs);\n"
  "}\n"
  "\n"
  "function markFrameDrawn() {\n"
  "  lastFrameDrawAt = Date.now();\n"
  "  smoothedVideoAgeMs = 0;\n"
  "  updateHudMetrics();\n"
  "}\n"
  "\n"
  "function setWsHudState(nextState) {\n"
  "  wsHudState = nextState;\n"
  "  updateHudMetrics();\n"
  "}\n"
  "\n"
  "function syncSelectedDevice(devices) {\n"
  "  if (!Array.isArray(devices) || devices.length === 0 || pinnedDeviceId) return;\n"
  "  if (!devices.includes(deviceId)) {\n"
  "    deviceId = devices[0];\n"
  "    brokerQueuedFrame = null;\n"
  "    brokerFrameBusy = false;\n"
  "    lastFrameDrawAt = 0;\n"
  "    smoothedVideoAgeMs = 0;\n"
  "  }\n"
  "}\n"
  "\n"
  "function requestQuality(quality) {\n"
  "  const nextIdx = qualityList.indexOf(quality);\n"
  "  if (nextIdx >= 0) { resIdx = nextIdx; resLabel.textContent = quality; }\n"
  "  if (apModeActive) {\n"
  "    apPost(\"/api/control\", { quality });\n"
  "  } else {\n"
  "    send({ type: \"camera_quality\", deviceId, quality });\n"
  "  }\n"
  "}\n"
  "\n"
  "function ensureDefaultQuality() {\n"
  "  if (defaultQualityApplied) return;\n"
  "  defaultQualityApplied = true;\n"
  "  requestQuality(DEFAULT_CAMERA_QUALITY);\n"
  "}\n"
  "\n"
  "function getRemoteVideoUrl(id) {\n"
  "  return `${location.origin}/video/${encodeURIComponent(id)}`;\n"
  "}\n"
  "\n"
  "function setStreamUrl(nextUrl) {\n"
  "  if (nextUrl === streamUrl) return;\n"
  "  const oldUrl = streamUrl;\n"
  "  streamUrl = nextUrl || \"\";\n"
  "  streamEl.src = streamUrl;\n"
  "  if (oldUrl.startsWith(\"blob:\")) URL.revokeObjectURL(oldUrl);\n"
  "}\n"
  "\n"
  "function setCanvasVideoMode(enabled) {\n"
  "  brokerCanvasActive = enabled;\n"
  "  streamEl.style.display = enabled ? \"none\" : \"\";\n"
  "  streamCanvas.classList.toggle(\"visible\", enabled);\n"
  "  if (!enabled) {\n"
  "    brokerQueuedFrame = null;\n"
  "    brokerFrameBusy = false;\n"
  "  }\n"
  "}\n"
  "\n"
  "async function drawApFrame(blob) {\n"
  "  if (!blob || blob.size < 1024) return false;\n"
  "  const bitmap = await createImageBitmap(blob);\n"
  "  if (streamCanvas.width !== bitmap.width || streamCanvas.height !== bitmap.height) {\n"
  "    streamCanvas.width = bitmap.width;\n"
  "    streamCanvas.height = bitmap.height;\n"
  "  }\n"
  "  streamCanvasCtx.drawImage(bitmap, 0, 0, streamCanvas.width, streamCanvas.height);\n"
  "  bitmap.close();\n"
  "  markFrameDrawn();\n"
  "  return true;\n"
  "}\n"
  "\n"
  "async function startApVideoLoop() {\n"
  "  if (apVideoLoopActive) return;\n"
  "  apVideoLoopActive = true;\n"
  "  setCanvasVideoMode(true);\n"
  "\n"
  "  while (apModeActive) {\n"
  "    try {\n"
  "      const res = await fetch(`${ESP32_BASE}/jpg?ts=${Date.now()}`, { cache: \"no-store\" });\n"
  "      if (!res.ok) {\n"
  "        await wait(80);\n"
  "        continue;\n"
  "      }\n"
  "      const blob = await res.blob();\n"
  "      const drawn = await drawApFrame(blob);\n"
  "      if (!drawn) {\n"
  "        await wait(40);\n"
  "      }\n"
  "    } catch {\n"
  "      connLabel.textContent = \"video retry\";\n"
  "      await wait(120);\n"
  "    }\n"
  "  }\n"
  "\n"
  "  apVideoLoopActive = false;\n"
  "}\n"
  "\n"
  "// broker WebSocket 연결\n"
  "function stopWsHeartbeat() {\n"
  "  if (wsPingTimer) {\n"
  "    clearInterval(wsPingTimer);\n"
  "    wsPingTimer = 0;\n"
  "  }\n"
  "}\n"
  "\n"
  "function startWsHeartbeat() {\n"
  "  stopWsHeartbeat();\n"
  "  wsPingTimer = setInterval(() => {\n"
  "    if (!wsReady || !ws || ws.readyState !== WebSocket.OPEN) return;\n"
  "    lastPingSentAt = performance.now();\n"
  "    ws.send(JSON.stringify({ type: \"ping\" }));\n"
  "  }, WS_PING_INTERVAL_MS);\n"
  "}\n"
  "\n"
  "function connectWS() {\n"
  "  if (!brokerUrl) return;\n"
  "  setWsHudState(\"OPENING\");\n"
  "  ws = new WebSocket(brokerUrl);\n"
  "  ws.binaryType = \"blob\";\n"
  "  ws.onopen = () => {\n"
  "    wsReady = true;\n"
  "    setWsHudState(\"OPEN\");\n"
  "    connLabel.textContent = \"broker on\";\n"
  "    startWsHeartbeat();\n"
  "  };\n"
  "  ws.onclose = () => {\n"
  "    wsReady = false; connLabel.textContent = \"reconnecting\";\n"
  "    setWsHudState(\"RETRY\");\n"
  "    stopWsHeartbeat();\n"
  "    setCanvasVideoMode(false);\n"
  "    setStreamUrl(\"\"); setTimeout(connectWS, 1500);\n"
  "  };\n"
  "  ws.onerror = () => { connLabel.textContent = \"socket error\"; setWsHudState(\"ERR\"); };\n"
  "  ws.onmessage = async (event) => {\n"
  "    if (typeof event.data === \"string\") {\n"
  "      try { handleBrokerMessage(JSON.parse(event.data)); } catch { connLabel.textContent = \"bad packet\"; }\n"
  "      return;\n"
  "    }\n"
  "    await handleBrokerBinary(event.data);\n"
  "  };\n"
  "}\n"
  "\n"
  "async function drawBrokerFrame(blob) {\n"
  "  if (!blob || blob.size < 1024) return;\n"
  "  setCanvasVideoMode(true);\n"
  "  const bitmap = await createImageBitmap(blob);\n"
  "  if (streamCanvas.width !== bitmap.width || streamCanvas.height !== bitmap.height) {\n"
  "    streamCanvas.width = bitmap.width;\n"
  "    streamCanvas.height = bitmap.height;\n"
  "  }\n"
  "  streamCanvasCtx.drawImage(bitmap, 0, 0, streamCanvas.width, streamCanvas.height);\n"
  "  bitmap.close();\n"
  "  markFrameDrawn();\n"
  "}\n"
  "\n"
  "async function flushBrokerFrameQueue() {\n"
  "  if (brokerFrameBusy || !brokerQueuedFrame) return;\n"
  "  brokerFrameBusy = true;\n"
  "  const nextFrame = brokerQueuedFrame;\n"
  "  brokerQueuedFrame = null;\n"
  "  try {\n"
  "    await drawBrokerFrame(nextFrame);\n"
  "  } catch {\n"
  "    connLabel.textContent = \"video retry\";\n"
  "  } finally {\n"
  "    brokerFrameBusy = false;\n"
  "    if (brokerQueuedFrame) {\n"
  "      queueMicrotask(flushBrokerFrameQueue);\n"
  "    }\n"
  "  }\n"
  "}\n"
  "\n"
  "async function handleBrokerBinary(frameBlob) {\n"
  "  const packet = await frameBlob.arrayBuffer();\n"
  "  const view = new DataView(packet);\n"
  "  if (view.byteLength < 4 || view.getUint8(0) !== 1) return;\n"
  "  const deviceIdLen = view.getUint16(1);\n"
  "  const frameStart = 3 + deviceIdLen;\n"
  "  if (view.byteLength <= frameStart) return;\n"
  "  const packetDeviceId = new TextDecoder().decode(new Uint8Array(packet, 3, deviceIdLen));\n"
  "  if (packetDeviceId !== deviceId) return;\n"
  "  brokerQueuedFrame = new Blob([packet.slice(frameStart)], { type: \"image/jpeg\" });\n"
  "  flushBrokerFrameQueue();\n"
  "}\n"
  "\n"
  "function handleBrokerMessage(message) {\n"
  "  if (message.type === \"welcome\") {\n"
  "    syncSelectedDevice(message.devices);\n"
  "    if (Array.isArray(message.devices) && message.devices.length > 0) {\n"
  "      connLabel.textContent = \"device online\";\n"
  "      setCanvasVideoMode(true);\n"
  "      ensureDefaultQuality();\n"
  "    } else {\n"
  "      connLabel.textContent = \"connected\";\n"
  "    }\n"
  "    return;\n"
  "  }\n"
  "  if (message.type === \"device_online\" && !pinnedDeviceId && !lastFrameDrawAt) {\n"
  "    deviceId = message.deviceId;\n"
  "  }\n"
  "  if (message.type === \"device_online\" && message.deviceId === deviceId) {\n"
  "    connLabel.textContent = \"device online\";\n"
  "    setCanvasVideoMode(true);\n"
  "    ensureDefaultQuality();\n"
  "    return;\n"
  "  }\n"
  "  if (message.type === \"device_offline\" && message.deviceId === deviceId) {\n"
  "    connLabel.textContent = \"device offline\";\n"
  "    setCanvasVideoMode(false);\n"
  "    setStreamUrl(\"\");\n"
  "    return;\n"
  "  }\n"
  "  if (message.type === \"status\" && message.deviceId === deviceId) {\n"
  "    if (typeof message.batteryPct === \"number\") batVal.textContent = `${message.batteryPct}%`;\n"
  "    else if (typeof message.batteryMv === \"number\") batVal.textContent = `${(message.batteryMv/1000).toFixed(2)}V`;\n"
  "    const sig = signalPercentFromRssi(message.rssi);\n"
  "    rssiVal.textContent = sig !== null ? `${sig}%` : \"--%\";\n"
  "    if (!apModeActive) setCanvasVideoMode(true);\n"
  "    return;\n"
  "  }\n"
  "  if (message.type === \"pong\" || message.type === \"broker_status\") {\n"
  "    if (message.type === \"broker_status\") {\n"
  "      syncSelectedDevice(message.devices);\n"
  "    }\n"
  "    if (message.type === \"pong\" && lastPingSentAt) {\n"
  "      lastPingRttMs = performance.now() - lastPingSentAt;\n"
  "      lastPingSentAt = 0;\n"
  "      updateHudMetrics();\n"
  "    }\n"
  "    return;\n"
  "  }\n"
  "  if (message.type === \"audio\" && message.deviceId === deviceId) {\n"
  "    playAudioChunk(message);\n"
  "  }\n"
  "}\n"
  "\n"
  "function cycleResolution() {\n"
  "  requestQuality(qualityList[(resIdx + 1) % qualityList.length]);\n"
  "}\n"
  "\n"
  "function toggleMode() {\n"
  "  driveMode = !driveMode;\n"
  "  modeLabel.textContent = driveMode ? \"조종 모드\" : \"감시 모드\";\n"
  "  setButtonState(btnNet, !driveMode);  // NET 버튼 재활용 안함 - 별도 처리\n"
  "  sendMode(driveMode ? \"drive\" : \"monitor\");\n"
  "}\n"
  "\n"
  "function toggleLed() {\n"
  "  ledOn = !ledOn;\n"
  "  setButtonState(btnLed, ledOn);\n"
  "  sendLed(ledOn);\n"
  "}\n"
  "\n"
  "async function doSnap() {\n"
  "  if (snapshotInFlight) return;\n"
  "  snapshotInFlight = true;\n"
  "  btnSnap.classList.add(\"active\");\n"
  "  const restoreQuality = qualityList[resIdx];\n"
  "  try {\n"
  "    const useCanvasVideo = apModeActive || brokerCanvasActive;\n"
  "    if (useCanvasVideo) {\n"
  "      if (!(streamCanvas.width > 0 && streamCanvas.height > 0)) return;\n"
  "    } else if (!streamEl.src) {\n"
  "      return;\n"
  "    }\n"
  "    if (restoreQuality !== \"UXGA\") { requestQuality(\"UXGA\"); await wait(1400); }\n"
  "    if (apModeActive) {\n"
  "      const res = await fetch(`${ESP32_BASE}/jpg?snap=${Date.now()}`, { cache: \"no-store\" });\n"
  "      const blob = await res.blob();\n"
  "      if (!blob || blob.size < 1024) return;\n"
  "      const url = URL.createObjectURL(blob);\n"
  "      const a = document.createElement(\"a\");\n"
  "      a.href = url; a.download = `rc-snap-${new Date().toISOString().replace(/[:.]/g,\"-\")}.jpg`;\n"
  "      a.click(); URL.revokeObjectURL(url);\n"
  "    } else {\n"
  "      snapshotCanvas.width = useCanvasVideo ? (streamCanvas.width || 1280) : (streamEl.naturalWidth || 1280);\n"
  "      snapshotCanvas.height = useCanvasVideo ? (streamCanvas.height || 720) : (streamEl.naturalHeight || 720);\n"
  "      const ctx = snapshotCanvas.getContext(\"2d\");\n"
  "      ctx.drawImage(useCanvasVideo ? streamCanvas : streamEl, 0, 0, snapshotCanvas.width, snapshotCanvas.height);\n"
  "      snapshotCanvas.toBlob((blob) => {\n"
  "        if (!blob) return;\n"
  "        const url = URL.createObjectURL(blob);\n"
  "        const a = document.createElement(\"a\");\n"
  "        a.href = url; a.download = `rc-snap-${new Date().toISOString().replace(/[:.]/g,\"-\")}.jpg`;\n"
  "        a.click(); URL.revokeObjectURL(url);\n"
  "      }, \"image/jpeg\", 0.96);\n"
  "    }\n"
  "  } catch {} finally {\n"
  "    if (restoreQuality !== \"UXGA\") requestQuality(restoreQuality);\n"
  "    snapshotInFlight = false;\n"
  "    setTimeout(() => btnSnap.classList.remove(\"active\"), 180);\n"
  "  }\n"
  "}\n"
  "\n"
  "// ============================================================\n"
  "// WiFi 패널\n"
  "// ============================================================\n"
  "let selectedSsid = null;\n"
  "let savedPasswords = {}; // {ssid: password} — ESP32에서 내려줌\n"
  "let scanResults = [];\n"
  "\n"
  "function openWifiPanel() {\n"
  "  if (!apModeActive) {\n"
  "    connLabel.textContent = \"AP mode only\";\n"
  "    return;\n"
  "  }\n"
  "  document.getElementById(\"wifi-overlay\").classList.add(\"open\");\n"
  "  document.getElementById(\"broker-hint\").style.display = \"block\";\n"
  "  setWifiStatus(\"\");\n"
  "  // 열릴 때 자동 스캔\n"
  "  doWifiScan();\n"
  "}\n"
  "\n"
  "function closeWifiPanel() {\n"
  "  document.getElementById(\"wifi-overlay\").classList.remove(\"open\");\n"
  "}\n"
  "\n"
  "function setWifiStatus(msg, type = \"\") {\n"
  "  const el = document.getElementById(\"wifi-status-msg\");\n"
  "  el.textContent = msg;\n"
  "  el.className = type ? type : \"\";\n"
  "}\n"
  "\n"
  "async function doWifiScan() {\n"
  "  const scanBtn = document.getElementById(\"wifi-scan-btn\");\n"
  "  const list = document.getElementById(\"wifi-scan-list\");\n"
  "  scanBtn.disabled = true;\n"
  "  scanBtn.innerHTML = '<span class=\"scan-spinner\">⟳</span> 스캔 중...';\n"
  "  list.innerHTML = '<div style=\"color:rgba(255,255,255,0.3);font-size:12px;text-align:center;padding:12px\">스캔 중...</div>';\n"
  "  setWifiStatus(\"\");\n"
  "\n"
  "  try {\n"
  "    let data = null;\n"
  "    for (let attempt = 0; attempt < 10; attempt++) {\n"
  "      const res = await fetch(`${ESP32_BASE || \"\"}/api/wifi-scan`);\n"
  "      data = await res.json();\n"
  "      if (!data?.scanning) break;\n"
  "      await new Promise((resolve) => setTimeout(resolve, 600));\n"
  "    }\n"
  "    scanResults = data.networks || [];\n"
  "    savedPasswords = data.saved || {};\n"
  "    renderScanList();\n"
  "  } catch {\n"
  "    list.innerHTML = '<div style=\"color:var(--red);font-size:12px;text-align:center;padding:12px\">스캔 실패</div>';\n"
  "    setWifiStatus(\"스캔 실패 — ESP32에 연결되어 있는지 확인하세요\", \"err\");\n"
  "  } finally {\n"
  "    scanBtn.disabled = false;\n"
  "    scanBtn.innerHTML = \"📡 다시 스캔\";\n"
  "  }\n"
  "}\n"
  "\n"
  "function renderScanList() {\n"
  "  const list = document.getElementById(\"wifi-scan-list\");\n"
  "  if (!scanResults.length) {\n"
  "    list.innerHTML = '<div style=\"color:rgba(255,255,255,0.3);font-size:12px;text-align:center;padding:12px\">주변 Wi-Fi 없음</div>';\n"
  "    return;\n"
  "  }\n"
  "  list.innerHTML = \"\";\n"
  "  for (const net of scanResults) {\n"
  "    const hasSaved = !!savedPasswords[net.ssid];\n"
  "    const div = document.createElement(\"div\");\n"
  "    div.className = \"wifi-item\";\n"
  "    div.innerHTML = `\n"
  "      <span class=\"wifi-item-ssid\">${escHtml(net.ssid)}</span>\n"
  "      <span class=\"wifi-item-meta\">\n"
  "        ${hasSaved ? '<span class=\"wifi-saved\">저장됨</span>' : \"\"}\n"
  "        ${net.secure ? '<span class=\"wifi-lock\">🔒</span>' : \"\"}\n"
  "        <span>${net.rssi ?? \"\"}dBm</span>\n"
  "      </span>`;\n"
  "    div.addEventListener(\"click\", (event) => selectSsid(net.ssid, net.secure, hasSaved, event));\n"
  "    list.appendChild(div);\n"
  "  }\n"
  "}\n"
  "\n"
  "function selectSsid(ssid, secure, hasSaved, event) {\n"
  "  selectedSsid = ssid;\n"
  "  selectedSsidSecure = secure;\n"
  "  // 기존 selected 해제\n"
  "  document.querySelectorAll(\".wifi-item\").forEach(el => el.classList.remove(\"selected\"));\n"
  "  event?.currentTarget?.classList.add(\"selected\");\n"
  "\n"
  "  const pwRow = document.getElementById(\"wifi-pw-row\");\n"
  "  const pwInput = document.getElementById(\"wifi-pw-input\");\n"
  "  const connectBtn = document.getElementById(\"wifi-connect-btn\");\n"
  "\n"
  "  if (hasSaved) {\n"
  "    // 저장된 비번 있음 → 비번 입력 숨김, 바로 연결 가능\n"
  "    pwRow.classList.remove(\"visible\");\n"
  "    pwInput.value = \"\";\n"
  "    connectBtn.disabled = false;\n"
  "    connectBtn.textContent = `\"${ssid}\" 로 연결 (저장된 비번 사용)`;\n"
  "  } else if (secure) {\n"
  "    // 비번 필요\n"
  "    pwRow.classList.add(\"visible\");\n"
  "    pwInput.value = \"\";\n"
  "    pwInput.focus();\n"
  "    connectBtn.disabled = false;\n"
  "    connectBtn.textContent = `\"${ssid}\" 로 연결`;\n"
  "  } else {\n"
  "    // 오픈 네트워크\n"
  "    pwRow.classList.remove(\"visible\");\n"
  "    pwInput.value = \"\";\n"
  "    connectBtn.disabled = false;\n"
  "    connectBtn.textContent = `\"${ssid}\" 로 연결 (오픈)`;\n"
  "  }\n"
  "  setWifiStatus(\"\");\n"
  "}\n"
  "\n"
  "async function doWifiConnect() {\n"
  "  if (!selectedSsid) return;\n"
  "  const pwInput = document.getElementById(\"wifi-pw-input\");\n"
  "  const connectBtn = document.getElementById(\"wifi-connect-btn\");\n"
  "  const password = pwInput.value;\n"
  "\n"
  "  connectBtn.disabled = true;\n"
  "  connectBtn.textContent = \"연결 중...\";\n"
  "  setWifiStatus(\"ESP32에 연결 요청 전송 중...\");\n"
  "\n"
  "  try {\n"
  "    const res = await fetch(`${ESP32_BASE || \"\"}/api/wifi-connect`, {\n"
  "      method: \"POST\",\n"
  "      headers: { \"Content-Type\": \"application/json\" },\n"
  "      body: JSON.stringify({\n"
  "        ssid: selectedSsid,\n"
  "        password: password,\n"
  "        secure: selectedSsidSecure\n"
  "      })\n"
  "    });\n"
  "    const data = await res.json();\n"
  "    if (data.ok) {\n"
  "      setWifiStatus(\"✅ 저장 완료. 브로커 모드로 전환 중입니다...\", \"ok\");\n"
  "      connectBtn.textContent = \"전환 중...\";\n"
  "      setTimeout(() => {\n"
  "        setWifiStatus(\"전환 후 브로커 페이지에서 다시 접속하세요\", \"ok\");\n"
  "        closeWifiPanel();\n"
  "      }, 4000);\n"
  "    } else {\n"
  "      setWifiStatus(`오류: ${data.reason || \"연결 실패\"}`, \"err\");\n"
  "      connectBtn.disabled = false;\n"
  "      connectBtn.textContent = `\"${selectedSsid}\" 로 연결`;\n"
  "    }\n"
  "  } catch {\n"
  "    setWifiStatus(\"ESP32 응답 없음. AP에 연결되어 있는지 확인하세요\", \"err\");\n"
  "    connectBtn.disabled = false;\n"
  "    connectBtn.textContent = `\"${selectedSsid}\" 로 연결`;\n"
  "  }\n"
  "}\n"
  "\n"
  "function escHtml(str) {\n"
  "  return String(str).replace(/&/g,\"&amp;\").replace(/</g,\"&lt;\").replace(/>/g,\"&gt;\").replace(/\"/g,\"&quot;\");\n"
  "}\n"
  "\n"
  "// ============================================================\n"
  "// ADPCM\n"
  "// ============================================================\n"
  "const IMA_INDEX_TABLE = [-1,-1,-1,-1,2,4,6,8,-1,-1,-1,-1,2,4,6,8];\n"
  "const IMA_STEP_TABLE = [7,8,9,10,11,12,13,14,16,17,19,21,23,25,28,31,34,37,41,45,50,55,60,66,73,80,88,97,107,118,130,143,157,173,190,209,230,253,279,307,337,371,408,449,494,544,598,658,724,796,876,963,1060,1166,1282,1411,1552,1707,1878,2066,2272,2499,2749,3024,3327,3660,4026,4428,4871,5358,5894,6484,7132,7845,8630,9493,10442,11487,12635,13899,15289,16818,18500,20350,22385,24623,27086,29794,32767];\n"
  "\n"
  "function decodeBase64ToBytes(encoded) {\n"
  "  const raw = atob(encoded); const bytes = new Uint8Array(raw.length);\n"
  "  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);\n"
  "  return bytes;\n"
  "}\n"
  "function encodeBytesToBase64(bytes) {\n"
  "  let b = \"\"; for (let i = 0; i < bytes.length; i++) b += String.fromCharCode(bytes[i]);\n"
  "  return btoa(b);\n"
  "}\n"
  "\n"
  "function decodeAdpcmChunk(bytes, sampleCount) {\n"
  "  if (!bytes.length || bytes.length < 4 || sampleCount <= 0) return new Float32Array(0);\n"
  "  let predictor = (bytes[1] << 8) | bytes[0];\n"
  "  if (predictor & 0x8000) predictor -= 0x10000;\n"
  "  let stepIndex = Math.max(0, Math.min(88, bytes[2] || 0));\n"
  "  const output = new Float32Array(sampleCount);\n"
  "  output[0] = predictor / 32768;\n"
  "  let outIndex = 1;\n"
  "  for (let i = 4; i < bytes.length && outIndex < sampleCount; i++) {\n"
  "    const packed = bytes[i];\n"
  "    for (const nibble of [packed & 0x0f, (packed >> 4) & 0x0f]) {\n"
  "      const step = IMA_STEP_TABLE[stepIndex];\n"
  "      let diff = step >> 3;\n"
  "      if (nibble & 1) diff += step >> 2;\n"
  "      if (nibble & 2) diff += step >> 1;\n"
  "      if (nibble & 4) diff += step;\n"
  "      predictor += (nibble & 8) ? -diff : diff;\n"
  "      predictor = Math.max(-32768, Math.min(32767, predictor));\n"
  "      stepIndex += IMA_INDEX_TABLE[nibble];\n"
  "      stepIndex = Math.max(0, Math.min(88, stepIndex));\n"
  "      output[outIndex++] = predictor / 32768;\n"
  "      if (outIndex >= sampleCount) break;\n"
  "    }\n"
  "  }\n"
  "  return output;\n"
  "}\n"
  "\n"
  "function encodeAdpcmChunk(samples) {\n"
  "  if (!samples.length) return new Uint8Array(0);\n"
  "  let predictor = samples[0];\n"
  "  let stepIndex = Math.max(0, Math.min(88, talkAudioState.stepIndex));\n"
  "  const output = new Uint8Array(4 + Math.ceil(Math.max(0, samples.length - 1) / 2));\n"
  "  output[0] = predictor & 0xff; output[1] = (predictor >> 8) & 0xff;\n"
  "  output[2] = stepIndex & 0xff; output[3] = 0;\n"
  "  let outIndex = 4;\n"
  "  for (let i = 1; i < samples.length; i += 2) {\n"
  "    let packed = 0;\n"
  "    for (let ni = 0; ni < 2; ni++) {\n"
  "      const sample = samples[i + ni];\n"
  "      if (typeof sample !== \"number\") continue;\n"
  "      const step = IMA_STEP_TABLE[stepIndex];\n"
  "      let diff = sample - predictor; let nibble = 0;\n"
  "      if (diff < 0) { nibble = 8; diff = -diff; }\n"
  "      let delta = step >> 3;\n"
  "      if (diff >= step) { nibble |= 4; diff -= step; delta += step; }\n"
  "      if (diff >= (step >> 1)) { nibble |= 2; diff -= step >> 1; delta += step >> 1; }\n"
  "      if (diff >= (step >> 2)) { nibble |= 1; delta += step >> 2; }\n"
  "      predictor += (nibble & 8) ? -delta : delta;\n"
  "      predictor = Math.max(-32768, Math.min(32767, predictor));\n"
  "      stepIndex += IMA_INDEX_TABLE[nibble & 0x0f];\n"
  "      stepIndex = Math.max(0, Math.min(88, stepIndex));\n"
  "      packed |= ni === 0 ? nibble : (nibble << 4);\n"
  "    }\n"
  "    output[outIndex++] = packed;\n"
  "  }\n"
  "  talkAudioState.stepIndex = stepIndex;\n"
  "  return output;\n"
  "}\n"
  "\n"
  "function resampleTalkSamples(floatSamples, inputRate, outputRate) {\n"
  "  if (!floatSamples.length) return [];\n"
  "  if (!inputRate || inputRate === outputRate) {\n"
  "    return Array.from(floatSamples, (sample) => Math.max(-32768, Math.min(32767, Math.round(sample * 32767))));\n"
  "  }\n"
  "\n"
  "  const ratio = inputRate / outputRate;\n"
  "  const outputLength = Math.max(1, Math.floor(floatSamples.length / ratio));\n"
  "  const output = new Array(outputLength);\n"
  "  let sourceIndex = 0;\n"
  "\n"
  "  for (let i = 0; i < outputLength; i++) {\n"
  "    const nextIndex = Math.min(floatSamples.length, Math.round((i + 1) * ratio));\n"
  "    let sum = 0;\n"
  "    let count = 0;\n"
  "    const endIndex = Math.max(sourceIndex + 1, nextIndex);\n"
  "    for (let j = sourceIndex; j < endIndex && j < floatSamples.length; j++) {\n"
  "      sum += floatSamples[j];\n"
  "      count++;\n"
  "    }\n"
  "    const averaged = count > 0 ? (sum / count) : floatSamples[Math.min(sourceIndex, floatSamples.length - 1)];\n"
  "    output[i] = Math.max(-32768, Math.min(32767, Math.round(averaged * 32767)));\n"
  "    sourceIndex = endIndex;\n"
  "  }\n"
  "\n"
  "  return output;\n"
  "}\n"
  "\n"
  "async function drainTalkUploadQueue() {\n"
  "  if (talkAudioState.uploadInFlight || !talkAudioState.uploadQueue.length) return;\n"
  "  talkAudioState.uploadInFlight = true;\n"
  "  while (talkAudioState.uploadQueue.length) {\n"
  "    const payload = talkAudioState.uploadQueue.shift();\n"
  "    const ok = await apPost(\"/api/talk-audio\", payload);\n"
  "    if (!ok) break;\n"
  "  }\n"
  "  talkAudioState.uploadInFlight = false;\n"
  "}\n"
  "\n"
  "function flushTalkSamples(force = false) {\n"
  "  const chunkSize = 640;\n"
  "  while (talkAudioState.pendingSamples.length >= chunkSize || (force && talkAudioState.pendingSamples.length > 1)) {\n"
  "    const take = talkAudioState.pendingSamples.length >= chunkSize ? chunkSize : talkAudioState.pendingSamples.length;\n"
  "    const chunk = talkAudioState.pendingSamples.splice(0, take);\n"
  "    const encoded = encodeAdpcmChunk(chunk);\n"
  "    if (!encoded.length) continue;\n"
  "    // AP모드에서도 로컬 WebSocket(또는 HTTP)으로 전송\n"
  "    if (apModeActive) {\n"
  "      talkAudioState.uploadQueue.push({\n"
  "        codec: \"adpcm_ima\", sampleRate: talkAudioState.targetSampleRate,\n"
  "        samples: chunk.length, seq: talkAudioState.seq++,\n"
  "        payload: encodeBytesToBase64(encoded)\n"
  "      });\n"
  "      drainTalkUploadQueue();\n"
  "    } else {\n"
  "      send({ type: \"talk_audio\", deviceId, codec: \"adpcm_ima\",\n"
  "        sampleRate: talkAudioState.targetSampleRate, samples: chunk.length,\n"
  "        seq: talkAudioState.seq++, payload: encodeBytesToBase64(encoded) });\n"
  "    }\n"
  "    talkAudioState.sentChunks++;\n"
  "  }\n"
  "}\n"
  "\n"
  "async function stopTalkCapture() {\n"
  "  flushTalkSamples(true);\n"
  "  talkAudioState.processor?.disconnect();\n"
  "  talkAudioState.source?.disconnect();\n"
  "  talkAudioState.muteGain?.disconnect();\n"
  "  talkAudioState.stream?.getTracks().forEach(t => t.stop());\n"
  "  if (talkAudioState.ctx) { try { await talkAudioState.ctx.close(); } catch {} }\n"
  "  talkAudioState.ctx = null; talkAudioState.stream = null;\n"
  "  talkAudioState.source = null; talkAudioState.processor = null;\n"
  "  talkAudioState.muteGain = null; talkAudioState.pendingSamples = [];\n"
  "  talkAudioState.uploadQueue = [];\n"
  "  talkAudioState.uploadInFlight = false;\n"
  "}\n"
  "\n"
  "async function ensureTalkCapture() {\n"
  "  if (talkAudioState.processor) return true;\n"
  "  const AudioContextCtor = window.AudioContext || window.webkitAudioContext;\n"
  "  try {\n"
  "    talkAudioState.ctx = new AudioContextCtor();\n"
  "    await talkAudioState.ctx.resume();\n"
  "    talkAudioState.captureSampleRate = talkAudioState.ctx.sampleRate || talkAudioState.targetSampleRate;\n"
  "    talkAudioState.stream = await navigator.mediaDevices.getUserMedia({\n"
  "      audio: { channelCount: 1, echoCancellation: true, noiseSuppression: true, autoGainControl: true }\n"
  "    });\n"
  "    talkAudioState.source = talkAudioState.ctx.createMediaStreamSource(talkAudioState.stream);\n"
  "    talkAudioState.processor = talkAudioState.ctx.createScriptProcessor(1024, 1, 1);\n"
  "    talkAudioState.muteGain = talkAudioState.ctx.createGain();\n"
  "    talkAudioState.muteGain.gain.value = 0;\n"
  "    talkAudioState.pendingSamples = []; talkAudioState.stepIndex = 0;\n"
  "    talkAudioState.processor.onaudioprocess = (event) => {\n"
  "      if (!talkOn) return;\n"
  "      if (!apModeActive && !wsReady) return;\n"
  "      const input = event.inputBuffer.getChannelData(0);\n"
  "      const resampled = resampleTalkSamples(input, talkAudioState.captureSampleRate, talkAudioState.targetSampleRate);\n"
  "      talkAudioState.pendingSamples.push(...resampled);\n"
  "      flushTalkSamples(false);\n"
  "    };\n"
  "    talkAudioState.source.connect(talkAudioState.processor);\n"
  "    talkAudioState.processor.connect(talkAudioState.muteGain);\n"
  "    talkAudioState.muteGain.connect(talkAudioState.ctx.destination);\n"
  "    return true;\n"
  "  } catch {\n"
  "    await stopTalkCapture(); return false;\n"
  "  }\n"
  "}\n"
  "\n"
  "async function ensureAudioContext(sampleRate = audioState.sampleRate) {\n"
  "  if (!audioState.ctx || audioState.sampleRate !== sampleRate) {\n"
  "    if (audioState.ctx) await audioState.ctx.close();\n"
  "    const AudioContextCtor = window.AudioContext || window.webkitAudioContext;\n"
  "    audioState.sampleRate = sampleRate;\n"
  "    audioState.ctx = new AudioContextCtor({ sampleRate });\n"
  "    audioState.mixDestination = audioState.ctx.createMediaStreamDestination();\n"
  "  }\n"
  "  if (audioState.ctx.state !== \"running\") await audioState.ctx.resume();\n"
  "}\n"
  "\n"
  "function armAudioPlayback() {\n"
  "  requestWakeLock();\n"
  "  if (audioState.enabled) return;\n"
  "  ensureAudioContext(audioState.sampleRate).then(() => {\n"
  "    audioState.enabled = true; audioState.nextPlayAt = 0;\n"
  "  }).catch(() => {});\n"
  "}\n"
  "\n"
  "function stopAudioPlayback() {\n"
  "  audioState.nextPlayAt = 0;\n"
  "  for (const source of audioState.activeSources) {\n"
  "    try { source.stop(); } catch {}\n"
  "  }\n"
  "  audioState.activeSources.clear();\n"
  "}\n"
  "\n"
  "function playAudioChunk(message) {\n"
  "  if (!audioState.enabled || !audioState.ctx || !message.payload || talkOn) return;\n"
  "  const bytes = decodeBase64ToBytes(message.payload);\n"
  "  const sampleRate = Number(message.sampleRate || 16000);\n"
  "  const samples = decodeAdpcmChunk(bytes, Number(message.samples || 0));\n"
  "  if (!samples.length) return;\n"
  "  const ctx = audioState.ctx;\n"
  "  const buffer = ctx.createBuffer(1, samples.length, sampleRate);\n"
  "  buffer.getChannelData(0).set(samples);\n"
  "  const now = ctx.currentTime;\n"
  "  if (!audioState.nextPlayAt || audioState.nextPlayAt < now - 0.04)\n"
  "    audioState.nextPlayAt = now + audioState.targetLeadSeconds;\n"
  "  if (audioState.nextPlayAt - now > audioState.maxLeadSeconds) {\n"
  "    audioState.nextPlayAt = now + audioState.targetLeadSeconds;\n"
  "  }\n"
  "  const source = ctx.createBufferSource();\n"
  "  source.buffer = buffer; source.connect(ctx.destination);\n"
  "  if (audioState.mixDestination) source.connect(audioState.mixDestination);\n"
  "  audioState.activeSources.add(source);\n"
  "  source.onended = () => audioState.activeSources.delete(source);\n"
  "  source.start(audioState.nextPlayAt);\n"
  "  audioState.nextPlayAt += buffer.duration;\n"
  "}\n"
  "\n"
  "// AP모드 오디오 폴링 (ESP32가 오디오 SSE 또는 WebSocket 지원하면 교체 가능)\n"
  "let apAudioWs = null;\n"
  "function startApAudioWs() {\n"
  "  if (!isApOrLocal || apAudioPaused) return;\n"
  "  const wsUrl = `ws://${location.hostname}:81/`;\n"
  "  try {\n"
  "    if (apAudioWs && (apAudioWs.readyState === WebSocket.OPEN || apAudioWs.readyState === WebSocket.CONNECTING)) {\n"
  "      return;\n"
  "    }\n"
  "    apAudioWs = new WebSocket(wsUrl);\n"
  "    apAudioWs.onmessage = (event) => {\n"
  "      try {\n"
  "        const msg = JSON.parse(event.data);\n"
  "        if (msg.type === \"audio\") playAudioChunk(msg);\n"
  "      } catch {}\n"
  "    };\n"
  "    apAudioWs.onerror = () => {\n"
  "      try { apAudioWs?.close(); } catch {}\n"
  "    };\n"
  "    apAudioWs.onclose = () => {\n"
  "      apAudioWs = null;\n"
  "      if (!apAudioPaused && apModeActive) {\n"
  "        setTimeout(startApAudioWs, 3000);\n"
  "      }\n"
  "    };\n"
  "  } catch {}\n"
  "}\n"
  "\n"
  "function pauseApMediaForTalk() {\n"
  "  if (!apModeActive) return;\n"
  "  window.clearTimeout(apResumeVideoTimer);\n"
  "  window.clearTimeout(apResumeAudioTimer);\n"
  "  apVideoPaused = true;\n"
  "  apAudioPaused = true;\n"
  "  talkOverlay.classList.add(\"visible\");\n"
  "  stopAudioPlayback();\n"
  "  if (apAudioWs) {\n"
  "    try { apAudioWs.close(); } catch {}\n"
  "    apAudioWs = null;\n"
  "  }\n"
  "}\n"
  "\n"
  "function resumeApMediaAfterTalk() {\n"
  "  if (!apModeActive) return;\n"
  "  window.clearTimeout(apResumeVideoTimer);\n"
  "  window.clearTimeout(apResumeAudioTimer);\n"
  "  talkOverlay.classList.remove(\"visible\");\n"
  "  apResumeVideoTimer = window.setTimeout(() => {\n"
  "    apVideoPaused = false;\n"
  "    if (!apVideoLoopActive) startApVideoLoop();\n"
  "  }, 250);\n"
  "  apResumeAudioTimer = window.setTimeout(() => {\n"
  "    apAudioPaused = false;\n"
  "    startApAudioWs();\n"
  "  }, 550);\n"
  "}\n"
  "\n"
  "// ============================================================\n"
  "// TALK\n"
  "// ============================================================\n"
  "async function talkStart() {\n"
  "  if (talkOn) return;\n"
  "  if (apModeActive) pauseApMediaForTalk();\n"
  "  stopAudioPlayback();\n"
  "  armAudioPlayback();\n"
  "  const ok = await ensureTalkCapture();\n"
  "  if (!ok) {\n"
  "    if (apModeActive) resumeApMediaAfterTalk();\n"
  "    return;\n"
  "  }\n"
  "  talkOn = true;\n"
  "  talkAudioState.sentChunks = 0;\n"
  "  setButtonState(btnTalk, true);\n"
  "  if (apModeActive) {\n"
  "    apPost(\"/api/control\", { talk: true });\n"
  "  } else {\n"
  "    send({ type: \"talk\", deviceId, enabled: true });\n"
  "  }\n"
  "}\n"
  "\n"
  "function beginTalkPress(event) {\n"
  "  event.preventDefault();\n"
  "  armAudioPlayback();\n"
  "  talkPointerId = event.pointerId ?? null;\n"
  "  if (typeof btnTalk.setPointerCapture === \"function\" && event.pointerId != null) {\n"
  "    try { btnTalk.setPointerCapture(event.pointerId); } catch {}\n"
  "  }\n"
  "  talkStart();\n"
  "}\n"
  "\n"
  "async function talkEnd() {\n"
  "  if (!talkOn) return;\n"
  "  talkOn = false;\n"
  "  talkPointerId = null;\n"
  "  setButtonState(btnTalk, false);\n"
  "  if (apModeActive) {\n"
  "    apPost(\"/api/control\", { talk: false });\n"
  "  } else {\n"
  "    send({ type: \"talk\", deviceId, enabled: false });\n"
  "  }\n"
  "  await stopTalkCapture();\n"
  "  if (apModeActive) resumeApMediaAfterTalk();\n"
  "}\n"
  "\n"
  "// ============================================================\n"
  "// REC\n"
  "// ============================================================\n"
  "async function toggleRec() {\n"
  "  if (recOn) { recorderState.recorder?.stop(); return; }\n"
  "  const useCanvasVideo = apModeActive || brokerCanvasActive;\n"
  "  const videoSource = useCanvasVideo ? streamCanvas : streamEl;\n"
  "  const hasVideo = useCanvasVideo\n"
  "    ? (streamCanvas.width > 0 && streamCanvas.height > 0)\n"
  "    : !!streamEl.src;\n"
  "  if (!hasVideo) return;\n"
  "  try {\n"
  "    const width = useCanvasVideo\n"
  "      ? (streamCanvas.width || 640)\n"
  "      : (streamEl.naturalWidth || 640);\n"
  "    const height = useCanvasVideo\n"
  "      ? (streamCanvas.height || 480)\n"
  "      : (streamEl.naturalHeight || 480);\n"
  "\n"
  "    if (useCanvasVideo) {\n"
  "      recorderState.stream = streamCanvas.captureStream(12);\n"
  "    } else {\n"
  "      snapshotCanvas.width = width; snapshotCanvas.height = height;\n"
  "      const snapshotCtx = snapshotCanvas.getContext(\"2d\");\n"
  "      recorderState.renderTimer = setInterval(() => {\n"
  "        try { snapshotCtx.drawImage(videoSource, 0, 0, width, height); } catch {}\n"
  "      }, 100);\n"
  "      recorderState.stream = snapshotCanvas.captureStream(12);\n"
  "    }\n"
  "\n"
  "    if (audioState.mixDestination) {\n"
  "      const [audioTrack] = audioState.mixDestination.stream.getAudioTracks();\n"
  "      if (audioTrack) recorderState.stream.addTrack(audioTrack);\n"
  "    }\n"
  "    recorderState.chunks = [];\n"
  "    recorderState.recorder = new MediaRecorder(recorderState.stream, { mimeType: \"video/webm\" });\n"
  "    recorderState.recorder.ondataavailable = (e) => { if (e.data.size > 0) recorderState.chunks.push(e.data); };\n"
  "    recorderState.recorder.onstop = () => {\n"
  "      if (recorderState.renderTimer) { clearInterval(recorderState.renderTimer); recorderState.renderTimer = null; }\n"
  "      recorderState.stream?.getTracks().forEach(t => t.stop());\n"
  "      const blob = new Blob(recorderState.chunks, { type: \"video/webm\" });\n"
  "      const url = URL.createObjectURL(blob);\n"
  "      const a = document.createElement(\"a\");\n"
  "      a.href = url; a.download = `rc-record-${new Date().toISOString().replace(/[:.]/g,\"-\")}.webm`;\n"
  "      a.click(); URL.revokeObjectURL(url);\n"
  "      recOn = false; setButtonState(btnRec, false); btnRec.textContent = \"REC\";\n"
  "      recorderState.stream = null; recorderState.recorder = null; recorderState.chunks = [];\n"
  "    };\n"
  "    recorderState.recorder.start();\n"
  "    recOn = true; setButtonState(btnRec, true); btnRec.textContent = \"REC\";\n"
  "  } catch {}\n"
  "}\n"
  "\n"
  "// ============================================================\n"
  "// 조이스틱\n"
  "// ============================================================\n"
  "let joystickActive = false, jCenterX = 0, jCenterY = 0, jMaxR = 0, lastSendTime = 0;\n"
  "const SEND_INTERVAL = 30;\n"
  "\n"
  "function getJoystickBounds() {\n"
  "  const r = outerEl.getBoundingClientRect();\n"
  "  const ringRect = document.getElementById(\"joystick-ring\").getBoundingClientRect();\n"
  "  jCenterX = r.left + r.width / 2; jCenterY = r.top + r.height / 2;\n"
  "  jMaxR = ringRect.width / 2;\n"
  "}\n"
  "\n"
  "function joystickMove(cx, cy) {\n"
  "  if (!driveMode) return;\n"
  "  let dx = cx - jCenterX, dy = cy - jCenterY;\n"
  "  const dist = Math.hypot(dx, dy);\n"
  "  if (dist > jMaxR) { dx *= jMaxR / dist; dy *= jMaxR / dist; }\n"
  "  knob.style.transform = `translate(${dx}px, ${dy}px)`;\n"
  "  const now = Date.now();\n"
  "  if (now - lastSendTime >= SEND_INTERVAL) {\n"
  "    sendCtrl(Math.round((-dy / jMaxR) * 100), Math.round((dx / jMaxR) * 100));\n"
  "    lastSendTime = now;\n"
  "  }\n"
  "}\n"
  "\n"
  "function joystickReset() {\n"
  "  joystickActive = false;\n"
  "  knob.style.transition = \"transform 0.2s\";\n"
  "  knob.style.transform = \"translate(0,0)\";\n"
  "  setTimeout(() => { knob.style.transition = \"\"; }, 200);\n"
  "  sendCtrl(0, 0);\n"
  "}\n"
  "\n"
  "outerEl.addEventListener(\"touchstart\", (e) => {\n"
  "  e.preventDefault(); armAudioPlayback(); getJoystickBounds();\n"
  "  if (!driveMode) return;\n"
  "  joystickActive = true; joystickMove(e.touches[0].clientX, e.touches[0].clientY);\n"
  "}, { passive: false });\n"
  "outerEl.addEventListener(\"touchmove\", (e) => {\n"
  "  e.preventDefault();\n"
  "  if (joystickActive) joystickMove(e.touches[0].clientX, e.touches[0].clientY);\n"
  "}, { passive: false });\n"
  "outerEl.addEventListener(\"touchend\", joystickReset);\n"
  "outerEl.addEventListener(\"touchcancel\", joystickReset);\n"
  "outerEl.addEventListener(\"mousedown\", (e) => {\n"
  "  armAudioPlayback(); getJoystickBounds();\n"
  "  if (!driveMode) return;\n"
  "  joystickActive = true; joystickMove(e.clientX, e.clientY);\n"
  "});\n"
  "window.addEventListener(\"resize\", getJoystickBounds);\n"
  "document.addEventListener(\"pointerdown\", armAudioPlayback, { passive: true });\n"
  "document.addEventListener(\"keydown\", armAudioPlayback);\n"
  "window.addEventListener(\"mousemove\", (e) => { if (joystickActive) joystickMove(e.clientX, e.clientY); });\n"
  "window.addEventListener(\"mouseup\", () => { if (joystickActive) joystickReset(); });\n"
  "\n"
  "// ============================================================\n"
  "// 버튼 이벤트\n"
  "// ============================================================\n"
  "btnLed.addEventListener(\"click\", () => { armAudioPlayback(); toggleLed(); });\n"
  "btnNet.addEventListener(\"click\", () => { armAudioPlayback(); openWifiPanel(); });\n"
  "btnSnap.addEventListener(\"click\", () => { armAudioPlayback(); doSnap(); });\n"
  "btnTalk.addEventListener(\"pointerdown\", beginTalkPress);\n"
  "btnTalk.addEventListener(\"pointerup\", (event) => {\n"
  "  if (talkPointerId === null || event.pointerId === talkPointerId) {\n"
  "    talkEnd();\n"
  "  }\n"
  "});\n"
  "btnTalk.addEventListener(\"pointercancel\", talkEnd);\n"
  "btnTalk.addEventListener(\"pointerleave\", talkEnd);\n"
  "btnTalk.addEventListener(\"lostpointercapture\", talkEnd);\n"
  "btnTalk.addEventListener(\"contextmenu\", (event) => event.preventDefault());\n"
  "btnRec.addEventListener(\"click\", () => { armAudioPlayback(); toggleRec(); });\n"
  "\n"
  "document.addEventListener(\"visibilitychange\", () => {\n"
  "  if (document.hidden) { talkEnd(); setCanvasVideoMode(false); setStreamUrl(\"\"); releaseWakeLock(); }\n"
  "  else { requestWakeLock(); }\n"
  "});\n"
  "window.addEventListener(\"pointerup\", talkEnd);\n"
  "window.addEventListener(\"blur\", talkEnd);\n"
  "window.addEventListener(\"pagehide\", () => { talkEnd(); setCanvasVideoMode(false); setStreamUrl(\"\"); releaseWakeLock(); });\n"
  "\n"
  "// ============================================================\n"
  "// 초기화\n"
  "// ============================================================\n"
  "if (isApOrLocal) {\n"
  "  // AP / 로컬 STA 모드\n"
  "  document.body.classList.add(\"ap-setup-only\");\n"
  "  setWsHudState(\"AP\");\n"
  "  connLabel.textContent = \"SETUP\";\n"
  "  resLabel.textContent = \"SETUP\";\n"
  "  startApStatusPoll();\n"
  "  setTimeout(openWifiPanel, 250);\n"
  "} else {\n"
  "  // broker 모드\n"
  "  apBanner.classList.remove(\"visible\");\n"
  "  resLabel.textContent = DEFAULT_CAMERA_QUALITY;\n"
  "  setWsHudState(\"OFF\");\n"
  "  connectWS();\n"
  "}\n"
  "\n"
  "hudTimer = window.setInterval(updateHudMetrics, 250);\n"
  "updateHudMetrics();\n"
  "</script>\n"
  "</body>\n"
  "</html>\n"
;
